package GUI;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.util.ArrayList;

public class AddScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddScreen
     */

    private ArrayList<JTextField> inputs;

    public AddScreen() {
        initComponents();
        inputs = new ArrayList<>();
        generateInputsArray();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        defaultBorder = new LineBorder(Color.BLACK);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cantonLabel = new javax.swing.JLabel();
        districtLabel = new javax.swing.JLabel();
        neighbourhoodLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        consumptionLabel = new javax.swing.JLabel();
        fatherLabel = new javax.swing.JLabel();
        cantonInput = new javax.swing.JTextField();
        cantonInput.setBorder(defaultBorder);
        districtInput = new javax.swing.JTextField();
        districtInput.setBorder(defaultBorder);
        IDInput = new javax.swing.JTextField();
        IDInput.setBorder(defaultBorder);
        consumptionInput = new javax.swing.JTextField();
        consumptionInput.setBorder(defaultBorder);
        neighbourhoodInput = new javax.swing.JTextField();
        neighbourhoodInput.setBorder(defaultBorder);
        fatherInput = new javax.swing.JTextField();
        fatherInput.setBorder(defaultBorder);
        jPanel1 = new javax.swing.JPanel();
        labelAddSensor = new javax.swing.JLabel();
        instructionsLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cantonLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cantonLabel.setText("Canton");

        districtLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        districtLabel.setText("Distrito");

        neighbourhoodLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        neighbourhoodLabel.setText("Barrio");

        IDLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IDLabel.setText("ID");

        consumptionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        consumptionLabel.setText("cm3/min");

        fatherLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fatherLabel.setText("Toma");

        labelAddSensor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelAddSensor.setText("Agregar Sensor");

        instructionsLabel.setText("Rellene la información solicitada y presione agregar.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(instructionsLabel)
                                        .addComponent(labelAddSensor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelAddSensor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(instructionsLabel)
                                .addGap(0, 8, Short.MAX_VALUE))
        );

        addButton.setText("agregar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(cantonLabel)
                                                                        .addComponent(IDLabel))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(IDInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cantonInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(neighbourhoodLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(neighbourhoodInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(districtLabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(districtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(consumptionLabel)
                                                                        .addComponent(fatherLabel))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(consumptionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(fatherInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addComponent(addButton)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cantonLabel)
                                        .addComponent(cantonInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IDLabel)
                                        .addComponent(IDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(districtLabel)
                                        .addComponent(districtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(neighbourhoodLabel)
                                        .addComponent(neighbourhoodInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(consumptionLabel)
                                        .addComponent(consumptionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fatherLabel)
                                        .addComponent(fatherInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(addButton)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {

        if (somethingEmpty()){
            markEmptyInputs();
        } else {
            resetInputs();
        }

    }

    private void resetInputs(){

        for (JTextField input : inputs){
            input.setText("");
            input.setBorder(defaultBorder);
        }

    }

    private boolean somethingEmpty(){
        return isEmpty(cantonInput)
                || isEmpty(IDInput)
                || isEmpty(districtInput)
                || isEmpty(neighbourhoodInput)
                || isEmpty(consumptionInput)
                || isEmpty(fatherInput);
    }

    private ArrayList<JTextField> emptyInputs(){
        ArrayList<JTextField> emptyInputs = new ArrayList<>();
        for (JTextField input:inputs){
            if (isEmpty(input)){
                emptyInputs.add(input);
            }
        }
        return emptyInputs;
    }

    private void markEmptyInputs(){
        ArrayList<JTextField> emptyInputs = emptyInputs();
        javax.swing.border.LineBorder required = new LineBorder(Color.RED);
        unmarkAlreadyEntered();
        for (JTextField input:emptyInputs){
            input.setBorder(required);
        }
    }

    private void unmarkAlreadyEntered(){
        for (JTextField input:inputs){
            if (!(isEmpty(input))){
                input.setBorder(defaultBorder);
            }
        }
    }


    private boolean isEmpty(JTextField pTextField){
        if (pTextField.getText().equals("")){
            return true;
        } else return false;
    }

    private void generateInputsArray(){
        inputs.add(cantonInput);
        inputs.add(IDInput);
        inputs.add(districtInput);
        inputs.add(neighbourhoodInput);
        inputs.add(consumptionInput);
        inputs.add(fatherInput);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField IDInput;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField cantonInput;
    private javax.swing.JLabel cantonLabel;
    private javax.swing.JTextField consumptionInput;
    private javax.swing.JLabel consumptionLabel;
    private javax.swing.JTextField districtInput;
    private javax.swing.JLabel districtLabel;
    private javax.swing.JTextField fatherInput;
    private javax.swing.JLabel fatherLabel;
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelAddSensor;
    private javax.swing.JTextField neighbourhoodInput;
    private javax.swing.JLabel neighbourhoodLabel;
    private LineBorder defaultBorder;
    // End of variables declaration


}
